language: python
python:
  - "3.7"
# command to install dependencies, requirements.txt should NOT include numpy
install:
  - pip install -r requirements.txt
# command to run tests
jobs:
  include:
    - stage: code_linting
      script:
        - pylint-fail-under --max-line-length=80 --fail_under 8.0 ctgan
        - flake8
    - stage: code_regression
      script:
        - pytest ctgan # or py.test for Python versions 3.5 and below
        - pytest --cov-report term --cov=ctgan --cov-fail-under=85 ctgan
    - stage: code